ShoppingCake.MVC/Models/ErrorViewModel.cs
using System;

namespace ShoppingCake.MVC.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ShoppingCake.MVC/Models/Products/ProductModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ShoppingCake.MVC.Models.Products
{
    public class ProductModel
    {
        public ProductModel(int id, string description, string image, int price, string productName)
        {
            Id = id;
            Description = description;
            Image = image;
            Price = price;
            ProductName = productName;
        }

        public int Id { get; set; }
        public string ProductName { get; set; }
        public decimal Price { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
    }
}

ShoppingCake.MVC/Models/Users/UserViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace ShoppingCake.MVC.Models.Users
{
    public class UserViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Telephone { get; set; }
        public string Email { get; set; }
        public DateTime BirthDate { get; set; }
        public string Password { get; set; }
        public string ConfirmPassword { get; set; }
    }
}

ShoppingCake.MVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ShoppingCake.MVC.Models;

namespace ShoppingCake.MVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ShoppingCake.MVC/Controllers/MenuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ShoppingCake.MVC.Models.Products;
using ShoppingCake.MVC.ViewsModels;

namespace ShoppingCake.MVC.Controllers
{
    public class MenuController : Controller
    {
        public IActionResult Index()
        {
            var viewModel = new MenuViewModel();
            List<ProductModel> products = new List<ProductModel>();
            products.Add(new ProductModel(1,"Maravilhoro bolo de chocolate","https://dummyimage.com/350x350/e02661/0015ff", 100,  "Bolo de Chocolate"));
            products.Add(new ProductModel(2, "Delicioso bolo de casadinho", "https://dummyimage.com/350x350/e02661/0015ff", 120, "Bolo de Casadinho"));
            products.Add(new ProductModel(3, "Expetacular bolo de churros", "https://dummyimage.com/350x350/e02661/0015ff", 110, "Bolo de Churros"));
            products.Add(new ProductModel(4, "Expetacular bolo de ninho", "https://dummyimage.com/350x350/e02661/0015ff", 125, "Bolo de ninho"));
            viewModel.Title = "Cardapio";
            viewModel.Products = products;
            return View(viewModel);
        }

        public IActionResult Detail(int id)
        {
            List<ProductModel> products = new List<ProductModel>();
            products.Add(new ProductModel(1, "Maravilhoro bolo de chocolate", "https://dummyimage.com/350x350/e02661/0015ff", 100, "Bolo de Chocolate"));
            products.Add(new ProductModel(2, "Delicioso bolo de casadinho", "https://dummyimage.com/350x350/e02661/0015ff", 120, "Bolo de Casadinho"));
            products.Add(new ProductModel(3, "Expetacular bolo de churros", "https://dummyimage.com/350x350/e02661/0015ff", 110, "Bolo de Churros"));
            products.Add(new ProductModel(4, "Expetacular bolo de ninho", "https://dummyimage.com/350x350/e02661/0015ff", 125, "Bolo de ninho"));
            var result = products.Where(x => x.Id == id).FirstOrDefault();
            return View(result);

        }

    }
}

ShoppingCake.MVC/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using ShoppingCake.Domain.Users;
using ShoppingCake.MVC.Models.Users;

namespace ShoppingCake.MVC.Controllers
{
    public class UserController : Controller
    {
        private readonly IUserRepository userRepository;

        public UserController(IUserRepository userRepository)
        {
            this.userRepository = userRepository;
        }

        public IActionResult Create()
        {
            return View();
        }

        public IActionResult Save(UserViewModel userViewModel)
        {

            userRepository.Add(new User {
                Name = userViewModel.Name, 
                BirthDate=userViewModel.BirthDate, 
                Email=userViewModel.Email, 
                Password=userViewModel.Password,
                Telephone = userViewModel.Telephone
            }); 
            return View("Success");
        }
    }
}

ShoppingCake.MVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Olá Ludy";
}

<div class="text-center">
    <h1 class="display-4">Bem vinda Ludy</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ShoppingCake.MVC/Views/Menu/Detail.cshtml
@model ShoppingCake.MVC.Models.Products.ProductModel;
@{
    ViewData["Title"] = "Detail";
}

<h1>Detail</h1>

<div class="row m-auto text-center w-75">
    <div class="img-wrap"><img src=@Model.Image></div>
    <div class="card-body bg-white mt-0 shadow">
        <ul class="list-unstyled mb-5 position-relative">
            <li>@Model.ProductName</li>
            <li><b>@Model.Price</b> R$</li>
            <li><b>50</b> fatias</li>
            <li><b>@Model.Description</b></li>
        </ul>
        <button type="button" class="btn btn-lg btn-block  btn-custom ">Comprar</button>
    </div>
</div>

ShoppingCake.MVC/Views/Menu/Index.cshtml
@model ShoppingCake.MVC.ViewsModels.MenuViewModel;
@{
    ViewData["Title"] = Model.Title;
}

<h1>@Model.Title</h1>
<div class="row">
    @foreach (var item in Model.Products)
    {
        <div class="col-md-4">
            <figure class="card card-product">
                <div class="img-wrap"><img src=@item.Image></div>
                <figcaption class="info-wrap">
                    <h4 class="title">@item.ProductName</h4>
                    <p class="desc">@item.Description</p>
                    <div class="rating-wrap">
                        <div class="label-rating">Bolo medio R$@item.Price</div>
                        <div class="label-rating">Bolo grande R$154</div>
                    </div> <!-- rating-wrap.// -->
                </figcaption>
                <div class="bottom-wrap">
                    @Html.ActionLink("Detalhe", "Detail", "Menu", new {id=item.Id }, new {@class= "btn btn-sm btn-primary float-right"})
                   
                    <div class="price-wrap h5">
                        <span class="price-new">Kit festa R$1280</span> <del class="price-old">R$1980</del>
                    </div> <!-- price-wrap.// -->
                </div> <!-- bottom-wrap.// -->
            </figure>
        </div>
    }
    <!-- col // -->


</div> <!-- row.// -->

ShoppingCake.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Shopping Cake</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Shopping Cake</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Menu" asp-action="Index">Cardápio</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Shopping Cake - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

ShoppingCake.MVC/Views/User/Create.cshtml
@model ShoppingCake.MVC.Models.Users.UserViewModel
<h1>Formulario de cadastro</h1>
@using (Html.BeginForm("Save", "User", null, FormMethod.Post)) { 
<fieldset>

    <!-- Text input-->
    <div class="form-group">
        <label class="col-md-4 control-label" for="textinput">Nome</label>
        <div class="col-md-4">
            @Html.TextBoxFor(model => model.Name, new { @class = "form-control input-md" })
        </div>
    </div>

    <!-- Text input-->
    <div class="form-group">
        <label class="col-md-4 control-label" for="">Telefone</label>
        <div class="col-md-4">
            @Html.TextBoxFor(model => model.Telephone, new { @class = "form-control input-md" })
        </div>
    </div>

    <!-- Text input-->
    <div class="form-group">
        <label class="col-md-4 control-label" for="">E-mail</label>
        <div class="col-md-4">
            @Html.TextBoxFor(model => model.Email, new { @class = "form-control input-md" })
        </div>
    </div>

    <!-- Text input-->
    <div class="form-group">
        <label class="col-md-4 control-label" for="textinput">Data de Nascimento</label>
        <div class="col-md-4">
            @Html.TextBoxFor(model => model.BirthDate, new { @class = "form-control input-md" })
        </div>
    </div>

    <!-- Password input-->
    <div class="form-group">
        <label class="col-md-4 control-label" for="">Senha</label>
        <div class="col-md-4">
            @Html.TextBoxFor(model => model.Password, new { @class = "form-control input-md", @type = "password" })
        </div>
    </div>

    <!-- Password input-->
    <div class="form-group">
        <label class="col-md-4 control-label" for="">Repetir a senha</label>
        <div class="col-md-4">
            @Html.TextBoxFor(model => model.ConfirmPassword, new { @class = "form-control input-md", @type = "password" })
        </div>
    </div>

    <!-- Button -->
    <div class="form-group">
        <label class="col-md-4 control-label" for=""></label>
        <div class="col-md-4">
            <button id="" name="" class="btn btn-primary" type="submit">Salvar</button>
        </div>
    </div>

</fieldset>
}

ShoppingCake.MVC/Views/User/Success.cshtml
<div class="row">
    <div class="col-sm-6 col-md-6">
        <div class="alert-message alert-message-success">
            <h4>
                Alert Message Success
            </h4>
            <p>
               Usuario criado com sucesso!
                <a href="http://www.jquery2dotnet.com/2013/07/cool-notification-css-style.html">
                    Cool Notification Css Style
                </a>
            </p>
        </div>
    </div>
    </div>